export const WHITE = [
  {pieceName: 'rook', row: 0, col: 0},
  {pieceName: 'knight', row: 0, col: 1},
  {pieceName: 'bishop', row: 0, col: 2},
  {pieceName: 'king', row: 0, col: 3},
  {pieceName: 'queen', row: 0, col: 4},
  {pieceName: 'bishop', row: 0, col: 5},
  {pieceName: 'knight', row: 0, col: 6},
  {pieceName: 'rook', row: 0, col: 7},
  {pieceName: 'pawn', row: 1, col: 0},
  {pieceName: 'pawn', row: 1, col: 1},
  {pieceName: 'pawn', row: 1, col: 2},
  {pieceName: 'pawn', row: 1, col: 3},
  {pieceName: 'pawn', row: 1, col: 4},
  {pieceName: 'pawn', row: 1, col: 5},
  {pieceName: 'pawn', row: 1, col: 6},
  {pieceName: 'pawn', row: 1, col: 7},
] as const

export const BLACK = [
  {pieceName: 'rook', row: 7, col: 0},
  {pieceName: 'knight', row: 7, col: 1},
  {pieceName: 'bishop', row: 7, col: 2},
  {pieceName: 'queen', row: 7, col: 3},
  {pieceName: 'king', row: 7, col: 4},
  {pieceName: 'bishop', row: 7, col: 5},
  {pieceName: 'knight', row: 7, col: 6},
  {pieceName: 'rook', row: 7, col: 7},
  {pieceName: 'pawn', row: 6, col: 0},
  {pieceName: 'pawn', row: 6, col: 1},
  {pieceName: 'pawn', row: 6, col: 2},
  {pieceName: 'pawn', row: 6, col: 3},
  {pieceName: 'pawn', row: 6, col: 4},
  {pieceName: 'pawn', row: 6, col: 5},
  {pieceName: 'pawn', row: 6, col: 6},
  {pieceName: 'pawn', row: 6, col: 7},
] as const