export const WHITE = {
  a1: {pieceName: 'rook', row: 0, col: 0},
  a2: {pieceName: 'knight', row: 0, col: 1},
  a3: {pieceName: 'bishop', row: 0, col: 2},
  a4: {pieceName: 'king', row: 0, col: 3},
  a5: {pieceName: 'queen', row: 0, col: 4},
  a6: {pieceName: 'bishop', row: 0, col: 5},
  a7: {pieceName: 'knight', row: 0, col: 6},
  a8: {pieceName: 'rook', row: 0, col: 7},
  b1: {pieceName: 'pawn', row: 1, col: 0},
  b2: {pieceName: 'pawn', row: 1, col: 1},
  b3: {pieceName: 'pawn', row: 1, col: 2},
  b4: {pieceName: 'pawn', row: 1, col: 3},
  b5: {pieceName: 'pawn', row: 1, col: 4},
  b6: {pieceName: 'pawn', row: 1, col: 5},
  b7: {pieceName: 'pawn', row: 1, col: 6},
  b8: {pieceName: 'pawn', row: 1, col: 7},
}

export const BLACK = {
  a1: {pieceName: 'rook', row: 7, col: 0},
  a2: {pieceName: 'knight', row: 7, col: 1},
  a3: {pieceName: 'bishop', row: 7, col: 2},
  a4: {pieceName: 'queen', row: 7, col: 3},
  a5: {pieceName: 'king', row: 7, col: 4},
  a6: {pieceName: 'bishop', row: 7, col: 5},
  a7: {pieceName: 'knight', row: 7, col: 6},
  a8: {pieceName: 'rook', row: 7, col: 7},
  b1: {pieceName: 'pawn', row: 6, col: 0},
  b2: {pieceName: 'pawn', row: 6, col: 1},
  b3: {pieceName: 'pawn', row: 6, col: 2},
  b4: {pieceName: 'pawn', row: 6, col: 3},
  b5: {pieceName: 'pawn', row: 6, col: 4},
  b6: {pieceName: 'pawn', row: 6, col: 5},
  b7: {pieceName: 'pawn', row: 6, col: 6},
  b8: {pieceName: 'pawn', row: 6, col: 7},
}